"""add period_of_day to routines

Revision ID: 07b3ee7c7879
Revises: ccbc10e0795d
Create Date: 2026-09-17 22:55:23.779435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07b3ee7c7879'
down_revision: Union[str, Sequence[str], None] = 'ccbc10e0795d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routines', sa.Column('period_of_day', sa.Enum('MORNING', 'AFTERNOON', 'EVENING', name='periodofday', native_enum=False), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routines', 'period_of_day')
    # ### end Alembic commands ###
