"""deletion_table__for_soft_delete

Revision ID: 1ada12d88dcf
Revises: 9060bc636274
Create Date: 2026-09-21 09:59:28.434157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ada12d88dcf'
down_revision: Union[str, Sequence[str], None] = '9060bc636274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deletions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('routine_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.Enum('routine_only', 'exclusive', name='deletionmode', native_enum=False), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('habits', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('habits', sa.Column('deletion_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'habits', 'deletions', ['deletion_id'], ['id'], ondelete='SET NULL')
    op.add_column('routines', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('routines', sa.Column('deletion_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'routines', 'deletions', ['deletion_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'routines', type_='foreignkey')
    op.drop_column('routines', 'deletion_id')
    op.drop_column('routines', 'deleted_at')
    op.drop_constraint(None, 'habits', type_='foreignkey')
    op.drop_column('habits', 'deletion_id')
    op.drop_column('habits', 'deleted_at')
    op.drop_table('deletions')
    # ### end Alembic commands ###
