"""user_plan_update

Revision ID: 340284b89d04
Revises: 67627add4578
Create Date: 2026-09-25 15:14:42.866777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '340284b89d04'
down_revision: Union[str, Sequence[str], None] = '67627add4578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_status', sa.Text(), server_default='basic', nullable=False))
    op.alter_column('users', 'plan',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'plan',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('users', 'subscription_status')
    # ### end Alembic commands ###
