"""routine_table__added_frequency

Revision ID: 6d384192eacd
Revises: 3698914c22f0
Create Date: 2026-09-18 14:33:35.789530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d384192eacd'
down_revision: Union[str, Sequence[str], None] = '3698914c22f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routines', sa.Column('frequency', sa.ARRAY(sa.Integer()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routines', 'frequency')
    # ### end Alembic commands ###
