"""habit_x_routine__many_to_many

Revision ID: 9060bc636274
Revises: a63193ce83b5
Create Date: 2026-09-19 19:18:07.084435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9060bc636274'
down_revision: Union[str, Sequence[str], None] = 'a63193ce83b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routine_habits',
    sa.Column('routine_id', sa.UUID(), nullable=False),
    sa.Column('habit_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['routine_id'], ['routines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('routine_id', 'habit_id')
    )
    op.drop_index(op.f('idx_habits_routine'), table_name='habits')
    op.drop_constraint(op.f('habits_routine_id_fkey'), 'habits', type_='foreignkey')
    op.drop_column('habits', 'routine_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('routine_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('habits_routine_id_fkey'), 'habits', 'routines', ['routine_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_habits_routine'), 'habits', ['routine_id'], unique=False)
    op.drop_table('routine_habits')
    # ### end Alembic commands ###
