"""added revenuecat add on

Revision ID: 948d3439a81d
Revises: 35b01cb3bef2
Create Date: 2026-09-07 21:27:49.395279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '948d3439a81d'
down_revision: Union[str, Sequence[str], None] = '35b01cb3bef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('revenuecat_id', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('plan_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'users', ['revenuecat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'plan_expires_at')
    op.drop_column('users', 'revenuecat_id')
    # ### end Alembic commands ###
