"""habit_x_routine__added_updated_at

Revision ID: a63193ce83b5
Revises: 6d384192eacd
Create Date: 2026-09-19 13:29:58.060199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a63193ce83b5'
down_revision: Union[str, Sequence[str], None] = '6d384192eacd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('routines', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routines', 'updated_at')
    op.drop_column('habits', 'updated_at')
    # ### end Alembic commands ###
