"""activity_logs_id

Revision ID: d0bc7bdd10f5
Revises: 340284b89d04
Create Date: 2026-09-28 12:13:12.644239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0bc7bdd10f5'
down_revision: Union[str, Sequence[str], None] = '340284b89d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the sequence default so postgres doesn't try to cast 'nextval(...)' to UUID
    op.alter_column('activity_log', 'id', server_default=None)
    op.alter_column('activity_log', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.UUID(),
               postgresql_using='gen_random_uuid()',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_log', 'id',
               existing_type=sa.UUID(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
